#!/bin/bash
# COLORS
# Black        0;30     Dark Gray     1;30
# Red          0;31     Light Red     1;31
# Green        0;32     Light Green   1;32
# Brown/Orange 0;33     Yellow        1;33
# Blue         0;34     Light Blue    1;34
# Purple       0;35     Light Purple  1;35
# Cyan         0;36     Light Cyan    1;36
# Light Gray   0;37     White         1;37
RED='\033[1;31m' # RED // For error message
NC='\033[0m' # No Color // Normal
CYAN='\033[1;36m' # Cyan
YELLOW='\033[1;33m' # Yellow
PURPLE='\033[1;35m' # Purple
LBLUE='\033[1;34m' # Light Blue
while true; do
printf "${CYAN}mp3, mp4, webm,${YELLOW} q, exit${NC}\n"
read type
if [[ "$type" == "mp3" ]]; then
printf "${PURPLE}Link: ${NC}"
read link
yt-dlp -x --audio-format mp3 "$link" -o /home/$USER/Music/"%(title)s.%(ext)s"
elif [[ "$type" == "mp4" ]]; then
printf "${PURPLE}Link: ${NC}"
read link
yt-dlp -f 22 "$link" -o /home/$USER/Videos/"%(title)s.%(ext)s"
elif [[ "$type" == "webm" ]]; then
printf "${PURPLE}Link: ${NC}"
read link
yt-dlp "$link" -o /home/$USER/Videos/"%(title)s.%(ext)s"
elif [[ "$type" == "q" || "$type" == "exit" ]]; then
break
else
printf "${RED}Oops, something went wrong. :(${NC}\n"
break
fi 
done
